---
apiVersion: policyGenerator/v1
kind: PolicyGenTemplate
metadata:
  # The name will be used to generate the placementBinding and placementRule names as {name}-placementBinding and {name}-placementRule
  name: "common-policies"
  namespace: "policy-template"
  labels:
    common: true
    groupName: "N/A"
    siteName: "N/A"
    # SNO must use the master MCP
    mcp: "master"
sourceFiles:
  - fileName: SriovSubscription
    policyName: "sriov-sub-policy"
  - fileName: SriovSubscriptionNS
    policyName: "sriov-sub-ns-policy"
  - fileName: SriovSubscriptionOperGroup
    policyName: "sriov-sub-oper-policy"
  - fileName: PtpSubscription
    policyName: "ptp-sub-policy"
  - fileName: PtpSubscriptionNS
    policyName: "ptp-sub-ns-policy"
  - fileName: PtpSubscriptionOperGroup
    policyName: "ptp-sub-oper-policy"
  - fileName: PaoSubscription
    policyName: "pao-sub-policy"
    spec:
    # Changing the channel value will upgrade/downgrade the operator installed version.
      channel: "4.8"
  - fileName: PaoSubscriptionNS
    policyName: "pao-sub-ns-policy"
  - fileName: PaoSubscriptionOperGroup
    policyName: "pao-sub-oper-policy"
  - fileName: PaoSubscriptionCatalogSource
    policyName: "pao-sub-catalog-policy"
  - fileName: ClusterLogSubscription
    policyName: "log-sub-policy"
  - fileName: MachineConfigContainerMountNS
    policyName: "worker-mc-mount-ns-policy"
    name: "02-worker-container-mount-namespace"
    labels:
      machineconfiguration.openshift.io/role: worker
  - fileName: MachineConfigContainerMountNS
    policyName: "master-mc-mount-ns-policy"
    name: "02-master-container-mount-namespace"
    labels:
      machineconfiguration.openshift.io/role: master
  - fileName: ConsoleOperatorDisable
    policyName: "console-policy"
  # Set ClusterLogForwarder & ClusterLogging as example might be better to create another policyTemp-Group
  - fileName: ClusterLogForwarder
    policyName: "log-forwarder-policy"
    spec:
      outputs:
        - type: "kafka"
          name: kafka-open
          # below url is an example
          url: tcp://10.46.55.190:9092/test
      pipelines:
        - name: audit-logs
          inputRefs:
           - audit
          outputRefs:
           - kafka-open
        - name: infrastructure-logs
          inputRefs:
           - infrastructure
          outputRefs:
           - kafka-open
  - fileName: ClusterLogging
    policyName: "log-policy"
    spec:
      curation:
        curator:
          schedule: "30 3 * * *"
      collection:
        logs:
          type: "fluentd"
          fluentd: {}
  - fileName: MachineConfigSctp
    policyName: "mc-sctp-policy"
    labels:
      machineconfiguration.openshift.io/role: master
  - fileName: MachineConfigDisableChronyd
    policyName: "mc-chronyd-policy"
  - fileName: PtpConfigSlave
    policyName: "ptp-config-policy"
    name: "du-ptp-slave"
    spec:
      profile:
      - name: "slave"
        interface: "ens5f0"
        ptp4lOpts: "-2 -s --summary_interval -4"
        phc2sysOpts: "-a -r -n 24"
  - fileName: SriovOperatorConfig
    policyName: "sriov-operconfig-policy"
  - fileName: SriovNetwork
    policyName: "sriov-nw-fh-policy"
    name: "sriov-nw-du-fh"
    spec:
      resourceName: du_fh
      vlan: 140
  - fileName: SriovNetworkNodePolicy
    policyName: "sriov-nnp-fh-policy"
    name: "sriov-nnp-du-fh"
    spec:
      deviceType: netdevice
      isRdma: true
      nicSelector:
        pfNames: ["ens5f0"]
      numVfs: 8
      priority: 10
      resourceName: du_fh
  - fileName: SriovNetwork
    policyName: "sriov-nw-mh-policy"
    name: "sriov-nw-du-mh"
    spec:
      resourceName: du_mh
      vlan: 150
  - fileName: SriovNetworkNodePolicy
    policyName: "sriov-nnp-mh-policy"
    name: "sriov-nnp-du-mh"
    spec:
      deviceType: vfio-pci
      isRdma: false
      nicSelector:
        pfNames: ["ens7f0"]
      numVfs: 8
      priority: 10
      resourceName: du_mh
  - fileName: PerformanceProfile
    name: "perfprofile-policy"
    policyName: "perfprofile-policy"
    spec:
      cpu:
        isolated: "4-7"
        reserved: "0-3"
      hugepages:
        defaultHugepagesSize: 1G
        pages:
          - size: 1G
            count: 1
