---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: common-policies-placementrule
  namespace: common-sub
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - key: name
      operator: NotIn
      values:
      - local-cluster
