# Not Used
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
    name: common-policies-placementrule
    namespace: common-sub
spec:
    clusterSelector:
        matchExpressions:
            - key: common
              operator: In
              values:
                - "true"
